[package]
name = "vaelix"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-window-handle = "0.5"
glutin = "0.32"
winit = "0.28"
gl = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
rustls = "0.20"
