// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: control.proto

#include "control.pb.h"
#include "control.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vaelix {
namespace control {

static const char* BrowserControlService_method_names[] = {
  "/vaelix.control.BrowserControlService/StartTab",
  "/vaelix.control.BrowserControlService/StopTab",
  "/vaelix.control.BrowserControlService/Navigate",
  "/vaelix.control.BrowserControlService/GetTabInfo",
  "/vaelix.control.BrowserControlService/Shutdown",
  "/vaelix.control.BrowserControlService/GetMetrics",
  "/vaelix.control.BrowserControlService/TabEvents",
};

std::unique_ptr< BrowserControlService::Stub> BrowserControlService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BrowserControlService::Stub> stub(new BrowserControlService::Stub(channel, options));
  return stub;
}

BrowserControlService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StartTab_(BrowserControlService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopTab_(BrowserControlService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Navigate_(BrowserControlService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTabInfo_(BrowserControlService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Shutdown_(BrowserControlService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMetrics_(BrowserControlService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TabEvents_(BrowserControlService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status BrowserControlService::Stub::StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::vaelix::control::StartTabResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartTab_, context, request, response);
}

void BrowserControlService::Stub::async::StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartTab_, context, request, response, std::move(f));
}

void BrowserControlService::Stub::async::StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartTab_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>* BrowserControlService::Stub::PrepareAsyncStartTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::control::StartTabResponse, ::vaelix::control::StartTabRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartTab_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>* BrowserControlService::Stub::AsyncStartTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartTabRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BrowserControlService::Stub::StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::vaelix::control::StopTabResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopTab_, context, request, response);
}

void BrowserControlService::Stub::async::StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopTab_, context, request, response, std::move(f));
}

void BrowserControlService::Stub::async::StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopTab_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>* BrowserControlService::Stub::PrepareAsyncStopTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::control::StopTabResponse, ::vaelix::control::StopTabRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopTab_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>* BrowserControlService::Stub::AsyncStopTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopTabRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BrowserControlService::Stub::Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::vaelix::control::NavigateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Navigate_, context, request, response);
}

void BrowserControlService::Stub::async::Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Navigate_, context, request, response, std::move(f));
}

void BrowserControlService::Stub::async::Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Navigate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>* BrowserControlService::Stub::PrepareAsyncNavigateRaw(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::control::NavigateResponse, ::vaelix::control::NavigateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Navigate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>* BrowserControlService::Stub::AsyncNavigateRaw(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNavigateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BrowserControlService::Stub::GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::vaelix::control::GetTabInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTabInfo_, context, request, response);
}

void BrowserControlService::Stub::async::GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTabInfo_, context, request, response, std::move(f));
}

void BrowserControlService::Stub::async::GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTabInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>* BrowserControlService::Stub::PrepareAsyncGetTabInfoRaw(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::control::GetTabInfoResponse, ::vaelix::control::GetTabInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTabInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>* BrowserControlService::Stub::AsyncGetTabInfoRaw(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTabInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BrowserControlService::Stub::Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::vaelix::control::BrowserShutdownResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Shutdown_, context, request, response);
}

void BrowserControlService::Stub::async::Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, std::move(f));
}

void BrowserControlService::Stub::async::Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>* BrowserControlService::Stub::PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::control::BrowserShutdownResponse, ::vaelix::control::BrowserShutdownRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Shutdown_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>* BrowserControlService::Stub::AsyncShutdownRaw(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShutdownRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BrowserControlService::Stub::GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::vaelix::control::GetBrowserMetricsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMetrics_, context, request, response);
}

void BrowserControlService::Stub::async::GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetrics_, context, request, response, std::move(f));
}

void BrowserControlService::Stub::async::GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetrics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>* BrowserControlService::Stub::PrepareAsyncGetMetricsRaw(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::control::GetBrowserMetricsResponse, ::vaelix::control::GetBrowserMetricsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMetrics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>* BrowserControlService::Stub::AsyncGetMetricsRaw(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetricsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* BrowserControlService::Stub::TabEventsRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>::Create(channel_.get(), rpcmethod_TabEvents_, context);
}

void BrowserControlService::Stub::async::TabEvents(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vaelix::control::TabEvent,::vaelix::control::TabEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::vaelix::control::TabEvent,::vaelix::control::TabEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_TabEvents_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* BrowserControlService::Stub::AsyncTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>::Create(channel_.get(), cq, rpcmethod_TabEvents_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* BrowserControlService::Stub::PrepareAsyncTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>::Create(channel_.get(), cq, rpcmethod_TabEvents_, context, false, nullptr);
}

BrowserControlService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BrowserControlService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BrowserControlService::Service, ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BrowserControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::control::StartTabRequest* req,
             ::vaelix::control::StartTabResponse* resp) {
               return service->StartTab(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BrowserControlService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BrowserControlService::Service, ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BrowserControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::control::StopTabRequest* req,
             ::vaelix::control::StopTabResponse* resp) {
               return service->StopTab(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BrowserControlService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BrowserControlService::Service, ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BrowserControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::control::NavigateRequest* req,
             ::vaelix::control::NavigateResponse* resp) {
               return service->Navigate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BrowserControlService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BrowserControlService::Service, ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BrowserControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::control::GetTabInfoRequest* req,
             ::vaelix::control::GetTabInfoResponse* resp) {
               return service->GetTabInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BrowserControlService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BrowserControlService::Service, ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BrowserControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::control::BrowserShutdownRequest* req,
             ::vaelix::control::BrowserShutdownResponse* resp) {
               return service->Shutdown(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BrowserControlService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BrowserControlService::Service, ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BrowserControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::control::GetBrowserMetricsRequest* req,
             ::vaelix::control::GetBrowserMetricsResponse* resp) {
               return service->GetMetrics(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BrowserControlService_method_names[6],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< BrowserControlService::Service, ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>(
          [](BrowserControlService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::vaelix::control::TabEvent,
             ::vaelix::control::TabEvent>* stream) {
               return service->TabEvents(ctx, stream);
             }, this)));
}

BrowserControlService::Service::~Service() {
}

::grpc::Status BrowserControlService::Service::StartTab(::grpc::ServerContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BrowserControlService::Service::StopTab(::grpc::ServerContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BrowserControlService::Service::Navigate(::grpc::ServerContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BrowserControlService::Service::GetTabInfo(::grpc::ServerContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BrowserControlService::Service::Shutdown(::grpc::ServerContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BrowserControlService::Service::GetMetrics(::grpc::ServerContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BrowserControlService::Service::TabEvents(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vaelix
}  // namespace control

