// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: plugin_api.proto

#include "plugin_api.pb.h"
#include "plugin_api.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vaelix {
namespace plugin {

static const char* PluginAPIService_method_names[] = {
  "/vaelix.plugin.PluginAPIService/LoadPlugin",
  "/vaelix.plugin.PluginAPIService/UnloadPlugin",
  "/vaelix.plugin.PluginAPIService/ListPlugins",
  "/vaelix.plugin.PluginAPIService/RegisterEventHook",
  "/vaelix.plugin.PluginAPIService/UnregisterEventHook",
  "/vaelix.plugin.PluginAPIService/ListEventHooks",
  "/vaelix.plugin.PluginAPIService/ApplyTheme",
  "/vaelix.plugin.PluginAPIService/GetThemes",
  "/vaelix.plugin.PluginAPIService/InstallTheme",
  "/vaelix.plugin.PluginAPIService/GetPluginConfig",
  "/vaelix.plugin.PluginAPIService/SetPluginConfig",
  "/vaelix.plugin.PluginAPIService/MakeNetworkRequest",
  "/vaelix.plugin.PluginAPIService/CreateWidget",
  "/vaelix.plugin.PluginAPIService/ModifyWidget",
  "/vaelix.plugin.PluginAPIService/PluginEventStream",
};

std::unique_ptr< PluginAPIService::Stub> PluginAPIService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PluginAPIService::Stub> stub(new PluginAPIService::Stub(channel, options));
  return stub;
}

PluginAPIService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_LoadPlugin_(PluginAPIService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnloadPlugin_(PluginAPIService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPlugins_(PluginAPIService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterEventHook_(PluginAPIService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnregisterEventHook_(PluginAPIService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListEventHooks_(PluginAPIService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ApplyTheme_(PluginAPIService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetThemes_(PluginAPIService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InstallTheme_(PluginAPIService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPluginConfig_(PluginAPIService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPluginConfig_(PluginAPIService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MakeNetworkRequest_(PluginAPIService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateWidget_(PluginAPIService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ModifyWidget_(PluginAPIService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PluginEventStream_(PluginAPIService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status PluginAPIService::Stub::LoadPlugin(::grpc::ClientContext* context, const ::vaelix::plugin::PluginLoadRequest& request, ::vaelix::plugin::PluginLoadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::PluginLoadRequest, ::vaelix::plugin::PluginLoadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoadPlugin_, context, request, response);
}

void PluginAPIService::Stub::async::LoadPlugin(::grpc::ClientContext* context, const ::vaelix::plugin::PluginLoadRequest* request, ::vaelix::plugin::PluginLoadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::PluginLoadRequest, ::vaelix::plugin::PluginLoadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadPlugin_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::LoadPlugin(::grpc::ClientContext* context, const ::vaelix::plugin::PluginLoadRequest* request, ::vaelix::plugin::PluginLoadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadPlugin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginLoadResponse>* PluginAPIService::Stub::PrepareAsyncLoadPluginRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginLoadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::PluginLoadResponse, ::vaelix::plugin::PluginLoadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoadPlugin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginLoadResponse>* PluginAPIService::Stub::AsyncLoadPluginRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginLoadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadPluginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::UnloadPlugin(::grpc::ClientContext* context, const ::vaelix::plugin::PluginUnloadRequest& request, ::vaelix::plugin::PluginUnloadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::PluginUnloadRequest, ::vaelix::plugin::PluginUnloadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnloadPlugin_, context, request, response);
}

void PluginAPIService::Stub::async::UnloadPlugin(::grpc::ClientContext* context, const ::vaelix::plugin::PluginUnloadRequest* request, ::vaelix::plugin::PluginUnloadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::PluginUnloadRequest, ::vaelix::plugin::PluginUnloadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnloadPlugin_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::UnloadPlugin(::grpc::ClientContext* context, const ::vaelix::plugin::PluginUnloadRequest* request, ::vaelix::plugin::PluginUnloadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnloadPlugin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginUnloadResponse>* PluginAPIService::Stub::PrepareAsyncUnloadPluginRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginUnloadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::PluginUnloadResponse, ::vaelix::plugin::PluginUnloadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnloadPlugin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginUnloadResponse>* PluginAPIService::Stub::AsyncUnloadPluginRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginUnloadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnloadPluginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::ListPlugins(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest& request, ::vaelix::plugin::PluginListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::PluginListRequest, ::vaelix::plugin::PluginListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListPlugins_, context, request, response);
}

void PluginAPIService::Stub::async::ListPlugins(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest* request, ::vaelix::plugin::PluginListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::PluginListRequest, ::vaelix::plugin::PluginListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPlugins_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::ListPlugins(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest* request, ::vaelix::plugin::PluginListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPlugins_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginListResponse>* PluginAPIService::Stub::PrepareAsyncListPluginsRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::PluginListResponse, ::vaelix::plugin::PluginListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListPlugins_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginListResponse>* PluginAPIService::Stub::AsyncListPluginsRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListPluginsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::RegisterEventHook(::grpc::ClientContext* context, const ::vaelix::plugin::RegisterEventHookRequest& request, ::vaelix::plugin::RegisterEventHookResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::RegisterEventHookRequest, ::vaelix::plugin::RegisterEventHookResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterEventHook_, context, request, response);
}

void PluginAPIService::Stub::async::RegisterEventHook(::grpc::ClientContext* context, const ::vaelix::plugin::RegisterEventHookRequest* request, ::vaelix::plugin::RegisterEventHookResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::RegisterEventHookRequest, ::vaelix::plugin::RegisterEventHookResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterEventHook_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::RegisterEventHook(::grpc::ClientContext* context, const ::vaelix::plugin::RegisterEventHookRequest* request, ::vaelix::plugin::RegisterEventHookResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterEventHook_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::RegisterEventHookResponse>* PluginAPIService::Stub::PrepareAsyncRegisterEventHookRaw(::grpc::ClientContext* context, const ::vaelix::plugin::RegisterEventHookRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::RegisterEventHookResponse, ::vaelix::plugin::RegisterEventHookRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterEventHook_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::RegisterEventHookResponse>* PluginAPIService::Stub::AsyncRegisterEventHookRaw(::grpc::ClientContext* context, const ::vaelix::plugin::RegisterEventHookRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterEventHookRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::UnregisterEventHook(::grpc::ClientContext* context, const ::vaelix::plugin::UnregisterEventHookRequest& request, ::vaelix::plugin::UnregisterEventHookResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::UnregisterEventHookRequest, ::vaelix::plugin::UnregisterEventHookResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnregisterEventHook_, context, request, response);
}

void PluginAPIService::Stub::async::UnregisterEventHook(::grpc::ClientContext* context, const ::vaelix::plugin::UnregisterEventHookRequest* request, ::vaelix::plugin::UnregisterEventHookResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::UnregisterEventHookRequest, ::vaelix::plugin::UnregisterEventHookResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnregisterEventHook_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::UnregisterEventHook(::grpc::ClientContext* context, const ::vaelix::plugin::UnregisterEventHookRequest* request, ::vaelix::plugin::UnregisterEventHookResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnregisterEventHook_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::UnregisterEventHookResponse>* PluginAPIService::Stub::PrepareAsyncUnregisterEventHookRaw(::grpc::ClientContext* context, const ::vaelix::plugin::UnregisterEventHookRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::UnregisterEventHookResponse, ::vaelix::plugin::UnregisterEventHookRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnregisterEventHook_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::UnregisterEventHookResponse>* PluginAPIService::Stub::AsyncUnregisterEventHookRaw(::grpc::ClientContext* context, const ::vaelix::plugin::UnregisterEventHookRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnregisterEventHookRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::ListEventHooks(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest& request, ::vaelix::plugin::PluginEventHooksResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::PluginListRequest, ::vaelix::plugin::PluginEventHooksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListEventHooks_, context, request, response);
}

void PluginAPIService::Stub::async::ListEventHooks(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest* request, ::vaelix::plugin::PluginEventHooksResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::PluginListRequest, ::vaelix::plugin::PluginEventHooksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListEventHooks_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::ListEventHooks(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest* request, ::vaelix::plugin::PluginEventHooksResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListEventHooks_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginEventHooksResponse>* PluginAPIService::Stub::PrepareAsyncListEventHooksRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::PluginEventHooksResponse, ::vaelix::plugin::PluginListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListEventHooks_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::PluginEventHooksResponse>* PluginAPIService::Stub::AsyncListEventHooksRaw(::grpc::ClientContext* context, const ::vaelix::plugin::PluginListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListEventHooksRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::ApplyTheme(::grpc::ClientContext* context, const ::vaelix::plugin::ApplyThemeRequest& request, ::vaelix::plugin::ApplyThemeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::ApplyThemeRequest, ::vaelix::plugin::ApplyThemeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ApplyTheme_, context, request, response);
}

void PluginAPIService::Stub::async::ApplyTheme(::grpc::ClientContext* context, const ::vaelix::plugin::ApplyThemeRequest* request, ::vaelix::plugin::ApplyThemeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::ApplyThemeRequest, ::vaelix::plugin::ApplyThemeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ApplyTheme_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::ApplyTheme(::grpc::ClientContext* context, const ::vaelix::plugin::ApplyThemeRequest* request, ::vaelix::plugin::ApplyThemeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ApplyTheme_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::ApplyThemeResponse>* PluginAPIService::Stub::PrepareAsyncApplyThemeRaw(::grpc::ClientContext* context, const ::vaelix::plugin::ApplyThemeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::ApplyThemeResponse, ::vaelix::plugin::ApplyThemeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ApplyTheme_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::ApplyThemeResponse>* PluginAPIService::Stub::AsyncApplyThemeRaw(::grpc::ClientContext* context, const ::vaelix::plugin::ApplyThemeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncApplyThemeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::GetThemes(::grpc::ClientContext* context, const ::vaelix::plugin::GetThemesRequest& request, ::vaelix::plugin::GetThemesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::GetThemesRequest, ::vaelix::plugin::GetThemesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetThemes_, context, request, response);
}

void PluginAPIService::Stub::async::GetThemes(::grpc::ClientContext* context, const ::vaelix::plugin::GetThemesRequest* request, ::vaelix::plugin::GetThemesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::GetThemesRequest, ::vaelix::plugin::GetThemesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetThemes_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::GetThemes(::grpc::ClientContext* context, const ::vaelix::plugin::GetThemesRequest* request, ::vaelix::plugin::GetThemesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetThemes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::GetThemesResponse>* PluginAPIService::Stub::PrepareAsyncGetThemesRaw(::grpc::ClientContext* context, const ::vaelix::plugin::GetThemesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::GetThemesResponse, ::vaelix::plugin::GetThemesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetThemes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::GetThemesResponse>* PluginAPIService::Stub::AsyncGetThemesRaw(::grpc::ClientContext* context, const ::vaelix::plugin::GetThemesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetThemesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::InstallTheme(::grpc::ClientContext* context, const ::vaelix::plugin::InstallThemeRequest& request, ::vaelix::plugin::InstallThemeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::InstallThemeRequest, ::vaelix::plugin::InstallThemeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InstallTheme_, context, request, response);
}

void PluginAPIService::Stub::async::InstallTheme(::grpc::ClientContext* context, const ::vaelix::plugin::InstallThemeRequest* request, ::vaelix::plugin::InstallThemeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::InstallThemeRequest, ::vaelix::plugin::InstallThemeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InstallTheme_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::InstallTheme(::grpc::ClientContext* context, const ::vaelix::plugin::InstallThemeRequest* request, ::vaelix::plugin::InstallThemeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InstallTheme_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::InstallThemeResponse>* PluginAPIService::Stub::PrepareAsyncInstallThemeRaw(::grpc::ClientContext* context, const ::vaelix::plugin::InstallThemeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::InstallThemeResponse, ::vaelix::plugin::InstallThemeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InstallTheme_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::InstallThemeResponse>* PluginAPIService::Stub::AsyncInstallThemeRaw(::grpc::ClientContext* context, const ::vaelix::plugin::InstallThemeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInstallThemeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::GetPluginConfig(::grpc::ClientContext* context, const ::vaelix::plugin::GetPluginConfigRequest& request, ::vaelix::plugin::GetPluginConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::GetPluginConfigRequest, ::vaelix::plugin::GetPluginConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPluginConfig_, context, request, response);
}

void PluginAPIService::Stub::async::GetPluginConfig(::grpc::ClientContext* context, const ::vaelix::plugin::GetPluginConfigRequest* request, ::vaelix::plugin::GetPluginConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::GetPluginConfigRequest, ::vaelix::plugin::GetPluginConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPluginConfig_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::GetPluginConfig(::grpc::ClientContext* context, const ::vaelix::plugin::GetPluginConfigRequest* request, ::vaelix::plugin::GetPluginConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPluginConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::GetPluginConfigResponse>* PluginAPIService::Stub::PrepareAsyncGetPluginConfigRaw(::grpc::ClientContext* context, const ::vaelix::plugin::GetPluginConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::GetPluginConfigResponse, ::vaelix::plugin::GetPluginConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPluginConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::GetPluginConfigResponse>* PluginAPIService::Stub::AsyncGetPluginConfigRaw(::grpc::ClientContext* context, const ::vaelix::plugin::GetPluginConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPluginConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::SetPluginConfig(::grpc::ClientContext* context, const ::vaelix::plugin::SetPluginConfigRequest& request, ::vaelix::plugin::SetPluginConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::SetPluginConfigRequest, ::vaelix::plugin::SetPluginConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPluginConfig_, context, request, response);
}

void PluginAPIService::Stub::async::SetPluginConfig(::grpc::ClientContext* context, const ::vaelix::plugin::SetPluginConfigRequest* request, ::vaelix::plugin::SetPluginConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::SetPluginConfigRequest, ::vaelix::plugin::SetPluginConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPluginConfig_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::SetPluginConfig(::grpc::ClientContext* context, const ::vaelix::plugin::SetPluginConfigRequest* request, ::vaelix::plugin::SetPluginConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPluginConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::SetPluginConfigResponse>* PluginAPIService::Stub::PrepareAsyncSetPluginConfigRaw(::grpc::ClientContext* context, const ::vaelix::plugin::SetPluginConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::SetPluginConfigResponse, ::vaelix::plugin::SetPluginConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPluginConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::SetPluginConfigResponse>* PluginAPIService::Stub::AsyncSetPluginConfigRaw(::grpc::ClientContext* context, const ::vaelix::plugin::SetPluginConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPluginConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::MakeNetworkRequest(::grpc::ClientContext* context, const ::vaelix::plugin::MakeNetworkRequestRequest& request, ::vaelix::plugin::MakeNetworkRequestResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::MakeNetworkRequestRequest, ::vaelix::plugin::MakeNetworkRequestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MakeNetworkRequest_, context, request, response);
}

void PluginAPIService::Stub::async::MakeNetworkRequest(::grpc::ClientContext* context, const ::vaelix::plugin::MakeNetworkRequestRequest* request, ::vaelix::plugin::MakeNetworkRequestResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::MakeNetworkRequestRequest, ::vaelix::plugin::MakeNetworkRequestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeNetworkRequest_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::MakeNetworkRequest(::grpc::ClientContext* context, const ::vaelix::plugin::MakeNetworkRequestRequest* request, ::vaelix::plugin::MakeNetworkRequestResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeNetworkRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::MakeNetworkRequestResponse>* PluginAPIService::Stub::PrepareAsyncMakeNetworkRequestRaw(::grpc::ClientContext* context, const ::vaelix::plugin::MakeNetworkRequestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::MakeNetworkRequestResponse, ::vaelix::plugin::MakeNetworkRequestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MakeNetworkRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::MakeNetworkRequestResponse>* PluginAPIService::Stub::AsyncMakeNetworkRequestRaw(::grpc::ClientContext* context, const ::vaelix::plugin::MakeNetworkRequestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMakeNetworkRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::CreateWidget(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetCreateRequest& request, ::vaelix::plugin::WidgetCreateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::WidgetCreateRequest, ::vaelix::plugin::WidgetCreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateWidget_, context, request, response);
}

void PluginAPIService::Stub::async::CreateWidget(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetCreateRequest* request, ::vaelix::plugin::WidgetCreateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::WidgetCreateRequest, ::vaelix::plugin::WidgetCreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateWidget_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::CreateWidget(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetCreateRequest* request, ::vaelix::plugin::WidgetCreateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateWidget_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::WidgetCreateResponse>* PluginAPIService::Stub::PrepareAsyncCreateWidgetRaw(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetCreateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::WidgetCreateResponse, ::vaelix::plugin::WidgetCreateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateWidget_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::WidgetCreateResponse>* PluginAPIService::Stub::AsyncCreateWidgetRaw(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetCreateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateWidgetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginAPIService::Stub::ModifyWidget(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetModifyRequest& request, ::vaelix::plugin::WidgetModifyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::plugin::WidgetModifyRequest, ::vaelix::plugin::WidgetModifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ModifyWidget_, context, request, response);
}

void PluginAPIService::Stub::async::ModifyWidget(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetModifyRequest* request, ::vaelix::plugin::WidgetModifyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::plugin::WidgetModifyRequest, ::vaelix::plugin::WidgetModifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModifyWidget_, context, request, response, std::move(f));
}

void PluginAPIService::Stub::async::ModifyWidget(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetModifyRequest* request, ::vaelix::plugin::WidgetModifyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModifyWidget_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::WidgetModifyResponse>* PluginAPIService::Stub::PrepareAsyncModifyWidgetRaw(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetModifyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::plugin::WidgetModifyResponse, ::vaelix::plugin::WidgetModifyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ModifyWidget_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::plugin::WidgetModifyResponse>* PluginAPIService::Stub::AsyncModifyWidgetRaw(::grpc::ClientContext* context, const ::vaelix::plugin::WidgetModifyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncModifyWidgetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>* PluginAPIService::Stub::PluginEventStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>::Create(channel_.get(), rpcmethod_PluginEventStream_, context);
}

void PluginAPIService::Stub::async::PluginEventStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vaelix::plugin::PluginEvent,::vaelix::plugin::PluginEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::vaelix::plugin::PluginEvent,::vaelix::plugin::PluginEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_PluginEventStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>* PluginAPIService::Stub::AsyncPluginEventStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>::Create(channel_.get(), cq, rpcmethod_PluginEventStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>* PluginAPIService::Stub::PrepareAsyncPluginEventStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>::Create(channel_.get(), cq, rpcmethod_PluginEventStream_, context, false, nullptr);
}

PluginAPIService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::PluginLoadRequest, ::vaelix::plugin::PluginLoadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::PluginLoadRequest* req,
             ::vaelix::plugin::PluginLoadResponse* resp) {
               return service->LoadPlugin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::PluginUnloadRequest, ::vaelix::plugin::PluginUnloadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::PluginUnloadRequest* req,
             ::vaelix::plugin::PluginUnloadResponse* resp) {
               return service->UnloadPlugin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::PluginListRequest, ::vaelix::plugin::PluginListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::PluginListRequest* req,
             ::vaelix::plugin::PluginListResponse* resp) {
               return service->ListPlugins(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::RegisterEventHookRequest, ::vaelix::plugin::RegisterEventHookResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::RegisterEventHookRequest* req,
             ::vaelix::plugin::RegisterEventHookResponse* resp) {
               return service->RegisterEventHook(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::UnregisterEventHookRequest, ::vaelix::plugin::UnregisterEventHookResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::UnregisterEventHookRequest* req,
             ::vaelix::plugin::UnregisterEventHookResponse* resp) {
               return service->UnregisterEventHook(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::PluginListRequest, ::vaelix::plugin::PluginEventHooksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::PluginListRequest* req,
             ::vaelix::plugin::PluginEventHooksResponse* resp) {
               return service->ListEventHooks(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::ApplyThemeRequest, ::vaelix::plugin::ApplyThemeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::ApplyThemeRequest* req,
             ::vaelix::plugin::ApplyThemeResponse* resp) {
               return service->ApplyTheme(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::GetThemesRequest, ::vaelix::plugin::GetThemesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::GetThemesRequest* req,
             ::vaelix::plugin::GetThemesResponse* resp) {
               return service->GetThemes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::InstallThemeRequest, ::vaelix::plugin::InstallThemeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::InstallThemeRequest* req,
             ::vaelix::plugin::InstallThemeResponse* resp) {
               return service->InstallTheme(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::GetPluginConfigRequest, ::vaelix::plugin::GetPluginConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::GetPluginConfigRequest* req,
             ::vaelix::plugin::GetPluginConfigResponse* resp) {
               return service->GetPluginConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::SetPluginConfigRequest, ::vaelix::plugin::SetPluginConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::SetPluginConfigRequest* req,
             ::vaelix::plugin::SetPluginConfigResponse* resp) {
               return service->SetPluginConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::MakeNetworkRequestRequest, ::vaelix::plugin::MakeNetworkRequestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::MakeNetworkRequestRequest* req,
             ::vaelix::plugin::MakeNetworkRequestResponse* resp) {
               return service->MakeNetworkRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::WidgetCreateRequest, ::vaelix::plugin::WidgetCreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::WidgetCreateRequest* req,
             ::vaelix::plugin::WidgetCreateResponse* resp) {
               return service->CreateWidget(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginAPIService::Service, ::vaelix::plugin::WidgetModifyRequest, ::vaelix::plugin::WidgetModifyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::plugin::WidgetModifyRequest* req,
             ::vaelix::plugin::WidgetModifyResponse* resp) {
               return service->ModifyWidget(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginAPIService_method_names[14],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< PluginAPIService::Service, ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>(
          [](PluginAPIService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::vaelix::plugin::PluginEvent,
             ::vaelix::plugin::PluginEvent>* stream) {
               return service->PluginEventStream(ctx, stream);
             }, this)));
}

PluginAPIService::Service::~Service() {
}

::grpc::Status PluginAPIService::Service::LoadPlugin(::grpc::ServerContext* context, const ::vaelix::plugin::PluginLoadRequest* request, ::vaelix::plugin::PluginLoadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::UnloadPlugin(::grpc::ServerContext* context, const ::vaelix::plugin::PluginUnloadRequest* request, ::vaelix::plugin::PluginUnloadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::ListPlugins(::grpc::ServerContext* context, const ::vaelix::plugin::PluginListRequest* request, ::vaelix::plugin::PluginListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::RegisterEventHook(::grpc::ServerContext* context, const ::vaelix::plugin::RegisterEventHookRequest* request, ::vaelix::plugin::RegisterEventHookResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::UnregisterEventHook(::grpc::ServerContext* context, const ::vaelix::plugin::UnregisterEventHookRequest* request, ::vaelix::plugin::UnregisterEventHookResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::ListEventHooks(::grpc::ServerContext* context, const ::vaelix::plugin::PluginListRequest* request, ::vaelix::plugin::PluginEventHooksResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::ApplyTheme(::grpc::ServerContext* context, const ::vaelix::plugin::ApplyThemeRequest* request, ::vaelix::plugin::ApplyThemeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::GetThemes(::grpc::ServerContext* context, const ::vaelix::plugin::GetThemesRequest* request, ::vaelix::plugin::GetThemesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::InstallTheme(::grpc::ServerContext* context, const ::vaelix::plugin::InstallThemeRequest* request, ::vaelix::plugin::InstallThemeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::GetPluginConfig(::grpc::ServerContext* context, const ::vaelix::plugin::GetPluginConfigRequest* request, ::vaelix::plugin::GetPluginConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::SetPluginConfig(::grpc::ServerContext* context, const ::vaelix::plugin::SetPluginConfigRequest* request, ::vaelix::plugin::SetPluginConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::MakeNetworkRequest(::grpc::ServerContext* context, const ::vaelix::plugin::MakeNetworkRequestRequest* request, ::vaelix::plugin::MakeNetworkRequestResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::CreateWidget(::grpc::ServerContext* context, const ::vaelix::plugin::WidgetCreateRequest* request, ::vaelix::plugin::WidgetCreateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::ModifyWidget(::grpc::ServerContext* context, const ::vaelix::plugin::WidgetModifyRequest* request, ::vaelix::plugin::WidgetModifyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginAPIService::Service::PluginEventStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vaelix::plugin::PluginEvent, ::vaelix::plugin::PluginEvent>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vaelix
}  // namespace plugin

