// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ui_events.proto

#include "ui_events.pb.h"
#include "ui_events.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vaelix {
namespace ui {

static const char* UIEventsService_method_names[] = {
  "/vaelix.ui.UIEventsService/StreamWindowEvents",
  "/vaelix.ui.UIEventsService/StreamTabEvents",
  "/vaelix.ui.UIEventsService/StreamInputEvents",
  "/vaelix.ui.UIEventsService/HandleNavigation",
  "/vaelix.ui.UIEventsService/HandleTabOperation",
  "/vaelix.ui.UIEventsService/HandleWindowOperation",
  "/vaelix.ui.UIEventsService/HandlePermission",
  "/vaelix.ui.UIEventsService/GetUIState",
  "/vaelix.ui.UIEventsService/GetWindowInfo",
  "/vaelix.ui.UIEventsService/GetTabStates",
};

std::unique_ptr< UIEventsService::Stub> UIEventsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UIEventsService::Stub> stub(new UIEventsService::Stub(channel, options));
  return stub;
}

UIEventsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamWindowEvents_(UIEventsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_StreamTabEvents_(UIEventsService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_StreamInputEvents_(UIEventsService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_HandleNavigation_(UIEventsService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleTabOperation_(UIEventsService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleWindowOperation_(UIEventsService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandlePermission_(UIEventsService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUIState_(UIEventsService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetWindowInfo_(UIEventsService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTabStates_(UIEventsService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReaderWriter< ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>* UIEventsService::Stub::StreamWindowEventsRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>::Create(channel_.get(), rpcmethod_StreamWindowEvents_, context);
}

void UIEventsService::Stub::async::StreamWindowEvents(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vaelix::ui::WindowEvent,::vaelix::ui::WindowEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::vaelix::ui::WindowEvent,::vaelix::ui::WindowEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamWindowEvents_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>* UIEventsService::Stub::AsyncStreamWindowEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>::Create(channel_.get(), cq, rpcmethod_StreamWindowEvents_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>* UIEventsService::Stub::PrepareAsyncStreamWindowEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>::Create(channel_.get(), cq, rpcmethod_StreamWindowEvents_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>* UIEventsService::Stub::StreamTabEventsRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>::Create(channel_.get(), rpcmethod_StreamTabEvents_, context);
}

void UIEventsService::Stub::async::StreamTabEvents(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vaelix::ui::TabEvent,::vaelix::ui::TabEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::vaelix::ui::TabEvent,::vaelix::ui::TabEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamTabEvents_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>* UIEventsService::Stub::AsyncStreamTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>::Create(channel_.get(), cq, rpcmethod_StreamTabEvents_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>* UIEventsService::Stub::PrepareAsyncStreamTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>::Create(channel_.get(), cq, rpcmethod_StreamTabEvents_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>* UIEventsService::Stub::StreamInputEventsRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>::Create(channel_.get(), rpcmethod_StreamInputEvents_, context);
}

void UIEventsService::Stub::async::StreamInputEvents(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vaelix::ui::InputEvent,::vaelix::ui::InputEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::vaelix::ui::InputEvent,::vaelix::ui::InputEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamInputEvents_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>* UIEventsService::Stub::AsyncStreamInputEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>::Create(channel_.get(), cq, rpcmethod_StreamInputEvents_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>* UIEventsService::Stub::PrepareAsyncStreamInputEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>::Create(channel_.get(), cq, rpcmethod_StreamInputEvents_, context, false, nullptr);
}

::grpc::Status UIEventsService::Stub::HandleNavigation(::grpc::ClientContext* context, const ::vaelix::ui::NavigationRequest& request, ::vaelix::ui::UIStateUpdate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::ui::NavigationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleNavigation_, context, request, response);
}

void UIEventsService::Stub::async::HandleNavigation(::grpc::ClientContext* context, const ::vaelix::ui::NavigationRequest* request, ::vaelix::ui::UIStateUpdate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::ui::NavigationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleNavigation_, context, request, response, std::move(f));
}

void UIEventsService::Stub::async::HandleNavigation(::grpc::ClientContext* context, const ::vaelix::ui::NavigationRequest* request, ::vaelix::ui::UIStateUpdate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleNavigation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::PrepareAsyncHandleNavigationRaw(::grpc::ClientContext* context, const ::vaelix::ui::NavigationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::ui::UIStateUpdate, ::vaelix::ui::NavigationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleNavigation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::AsyncHandleNavigationRaw(::grpc::ClientContext* context, const ::vaelix::ui::NavigationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleNavigationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UIEventsService::Stub::HandleTabOperation(::grpc::ClientContext* context, const ::vaelix::ui::TabOperationRequest& request, ::vaelix::ui::UIStateUpdate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::ui::TabOperationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleTabOperation_, context, request, response);
}

void UIEventsService::Stub::async::HandleTabOperation(::grpc::ClientContext* context, const ::vaelix::ui::TabOperationRequest* request, ::vaelix::ui::UIStateUpdate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::ui::TabOperationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleTabOperation_, context, request, response, std::move(f));
}

void UIEventsService::Stub::async::HandleTabOperation(::grpc::ClientContext* context, const ::vaelix::ui::TabOperationRequest* request, ::vaelix::ui::UIStateUpdate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleTabOperation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::PrepareAsyncHandleTabOperationRaw(::grpc::ClientContext* context, const ::vaelix::ui::TabOperationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::ui::UIStateUpdate, ::vaelix::ui::TabOperationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleTabOperation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::AsyncHandleTabOperationRaw(::grpc::ClientContext* context, const ::vaelix::ui::TabOperationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleTabOperationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UIEventsService::Stub::HandleWindowOperation(::grpc::ClientContext* context, const ::vaelix::ui::WindowOperationRequest& request, ::vaelix::ui::UIStateUpdate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::ui::WindowOperationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleWindowOperation_, context, request, response);
}

void UIEventsService::Stub::async::HandleWindowOperation(::grpc::ClientContext* context, const ::vaelix::ui::WindowOperationRequest* request, ::vaelix::ui::UIStateUpdate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::ui::WindowOperationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleWindowOperation_, context, request, response, std::move(f));
}

void UIEventsService::Stub::async::HandleWindowOperation(::grpc::ClientContext* context, const ::vaelix::ui::WindowOperationRequest* request, ::vaelix::ui::UIStateUpdate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleWindowOperation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::PrepareAsyncHandleWindowOperationRaw(::grpc::ClientContext* context, const ::vaelix::ui::WindowOperationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::ui::UIStateUpdate, ::vaelix::ui::WindowOperationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleWindowOperation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::AsyncHandleWindowOperationRaw(::grpc::ClientContext* context, const ::vaelix::ui::WindowOperationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleWindowOperationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UIEventsService::Stub::HandlePermission(::grpc::ClientContext* context, const ::vaelix::ui::PermissionRequest& request, ::vaelix::ui::UIStateUpdate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::ui::PermissionRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandlePermission_, context, request, response);
}

void UIEventsService::Stub::async::HandlePermission(::grpc::ClientContext* context, const ::vaelix::ui::PermissionRequest* request, ::vaelix::ui::UIStateUpdate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::ui::PermissionRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandlePermission_, context, request, response, std::move(f));
}

void UIEventsService::Stub::async::HandlePermission(::grpc::ClientContext* context, const ::vaelix::ui::PermissionRequest* request, ::vaelix::ui::UIStateUpdate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandlePermission_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::PrepareAsyncHandlePermissionRaw(::grpc::ClientContext* context, const ::vaelix::ui::PermissionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::ui::UIStateUpdate, ::vaelix::ui::PermissionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandlePermission_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::AsyncHandlePermissionRaw(::grpc::ClientContext* context, const ::vaelix::ui::PermissionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandlePermissionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UIEventsService::Stub::GetUIState(::grpc::ClientContext* context, const ::vaelix::ui::UIStateQuery& request, ::vaelix::ui::UIStateUpdate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::ui::UIStateQuery, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUIState_, context, request, response);
}

void UIEventsService::Stub::async::GetUIState(::grpc::ClientContext* context, const ::vaelix::ui::UIStateQuery* request, ::vaelix::ui::UIStateUpdate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::ui::UIStateQuery, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUIState_, context, request, response, std::move(f));
}

void UIEventsService::Stub::async::GetUIState(::grpc::ClientContext* context, const ::vaelix::ui::UIStateQuery* request, ::vaelix::ui::UIStateUpdate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUIState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::PrepareAsyncGetUIStateRaw(::grpc::ClientContext* context, const ::vaelix::ui::UIStateQuery& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::ui::UIStateUpdate, ::vaelix::ui::UIStateQuery, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUIState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::AsyncGetUIStateRaw(::grpc::ClientContext* context, const ::vaelix::ui::UIStateQuery& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUIStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UIEventsService::Stub::GetWindowInfo(::grpc::ClientContext* context, const ::vaelix::ui::WindowInfoRequest& request, ::vaelix::ui::WindowInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::ui::WindowInfoRequest, ::vaelix::ui::WindowInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetWindowInfo_, context, request, response);
}

void UIEventsService::Stub::async::GetWindowInfo(::grpc::ClientContext* context, const ::vaelix::ui::WindowInfoRequest* request, ::vaelix::ui::WindowInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::ui::WindowInfoRequest, ::vaelix::ui::WindowInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWindowInfo_, context, request, response, std::move(f));
}

void UIEventsService::Stub::async::GetWindowInfo(::grpc::ClientContext* context, const ::vaelix::ui::WindowInfoRequest* request, ::vaelix::ui::WindowInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWindowInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::WindowInfo>* UIEventsService::Stub::PrepareAsyncGetWindowInfoRaw(::grpc::ClientContext* context, const ::vaelix::ui::WindowInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::ui::WindowInfo, ::vaelix::ui::WindowInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetWindowInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::WindowInfo>* UIEventsService::Stub::AsyncGetWindowInfoRaw(::grpc::ClientContext* context, const ::vaelix::ui::WindowInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetWindowInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UIEventsService::Stub::GetTabStates(::grpc::ClientContext* context, const ::vaelix::ui::TabStatesRequest& request, ::vaelix::ui::UIStateUpdate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vaelix::ui::TabStatesRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTabStates_, context, request, response);
}

void UIEventsService::Stub::async::GetTabStates(::grpc::ClientContext* context, const ::vaelix::ui::TabStatesRequest* request, ::vaelix::ui::UIStateUpdate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vaelix::ui::TabStatesRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTabStates_, context, request, response, std::move(f));
}

void UIEventsService::Stub::async::GetTabStates(::grpc::ClientContext* context, const ::vaelix::ui::TabStatesRequest* request, ::vaelix::ui::UIStateUpdate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTabStates_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::PrepareAsyncGetTabStatesRaw(::grpc::ClientContext* context, const ::vaelix::ui::TabStatesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vaelix::ui::UIStateUpdate, ::vaelix::ui::TabStatesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTabStates_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vaelix::ui::UIStateUpdate>* UIEventsService::Stub::AsyncGetTabStatesRaw(::grpc::ClientContext* context, const ::vaelix::ui::TabStatesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTabStatesRaw(context, request, cq);
  result->StartCall();
  return result;
}

UIEventsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< UIEventsService::Service, ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::vaelix::ui::WindowEvent,
             ::vaelix::ui::WindowEvent>* stream) {
               return service->StreamWindowEvents(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< UIEventsService::Service, ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::vaelix::ui::TabEvent,
             ::vaelix::ui::TabEvent>* stream) {
               return service->StreamTabEvents(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< UIEventsService::Service, ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::vaelix::ui::InputEvent,
             ::vaelix::ui::InputEvent>* stream) {
               return service->StreamInputEvents(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UIEventsService::Service, ::vaelix::ui::NavigationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::ui::NavigationRequest* req,
             ::vaelix::ui::UIStateUpdate* resp) {
               return service->HandleNavigation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UIEventsService::Service, ::vaelix::ui::TabOperationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::ui::TabOperationRequest* req,
             ::vaelix::ui::UIStateUpdate* resp) {
               return service->HandleTabOperation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UIEventsService::Service, ::vaelix::ui::WindowOperationRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::ui::WindowOperationRequest* req,
             ::vaelix::ui::UIStateUpdate* resp) {
               return service->HandleWindowOperation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UIEventsService::Service, ::vaelix::ui::PermissionRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::ui::PermissionRequest* req,
             ::vaelix::ui::UIStateUpdate* resp) {
               return service->HandlePermission(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UIEventsService::Service, ::vaelix::ui::UIStateQuery, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::ui::UIStateQuery* req,
             ::vaelix::ui::UIStateUpdate* resp) {
               return service->GetUIState(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UIEventsService::Service, ::vaelix::ui::WindowInfoRequest, ::vaelix::ui::WindowInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::ui::WindowInfoRequest* req,
             ::vaelix::ui::WindowInfo* resp) {
               return service->GetWindowInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UIEventsService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UIEventsService::Service, ::vaelix::ui::TabStatesRequest, ::vaelix::ui::UIStateUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UIEventsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vaelix::ui::TabStatesRequest* req,
             ::vaelix::ui::UIStateUpdate* resp) {
               return service->GetTabStates(ctx, req, resp);
             }, this)));
}

UIEventsService::Service::~Service() {
}

::grpc::Status UIEventsService::Service::StreamWindowEvents(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vaelix::ui::WindowEvent, ::vaelix::ui::WindowEvent>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::StreamTabEvents(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vaelix::ui::TabEvent, ::vaelix::ui::TabEvent>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::StreamInputEvents(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vaelix::ui::InputEvent, ::vaelix::ui::InputEvent>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::HandleNavigation(::grpc::ServerContext* context, const ::vaelix::ui::NavigationRequest* request, ::vaelix::ui::UIStateUpdate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::HandleTabOperation(::grpc::ServerContext* context, const ::vaelix::ui::TabOperationRequest* request, ::vaelix::ui::UIStateUpdate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::HandleWindowOperation(::grpc::ServerContext* context, const ::vaelix::ui::WindowOperationRequest* request, ::vaelix::ui::UIStateUpdate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::HandlePermission(::grpc::ServerContext* context, const ::vaelix::ui::PermissionRequest* request, ::vaelix::ui::UIStateUpdate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::GetUIState(::grpc::ServerContext* context, const ::vaelix::ui::UIStateQuery* request, ::vaelix::ui::UIStateUpdate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::GetWindowInfo(::grpc::ServerContext* context, const ::vaelix::ui::WindowInfoRequest* request, ::vaelix::ui::WindowInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UIEventsService::Service::GetTabStates(::grpc::ServerContext* context, const ::vaelix::ui::TabStatesRequest* request, ::vaelix::ui::UIStateUpdate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vaelix
}  // namespace ui

