// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: control.proto
#ifndef GRPC_control_2eproto__INCLUDED
#define GRPC_control_2eproto__INCLUDED

#include "control.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vaelix {
namespace control {

// gRPC Service Definition
class BrowserControlService final {
 public:
  static constexpr char const* service_full_name() {
    return "vaelix.control.BrowserControlService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Tab lifecycle management
    virtual ::grpc::Status StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::vaelix::control::StartTabResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StartTabResponse>> AsyncStartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StartTabResponse>>(AsyncStartTabRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StartTabResponse>> PrepareAsyncStartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StartTabResponse>>(PrepareAsyncStartTabRaw(context, request, cq));
    }
    virtual ::grpc::Status StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::vaelix::control::StopTabResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StopTabResponse>> AsyncStopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StopTabResponse>>(AsyncStopTabRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StopTabResponse>> PrepareAsyncStopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StopTabResponse>>(PrepareAsyncStopTabRaw(context, request, cq));
    }
    virtual ::grpc::Status Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::vaelix::control::NavigateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::NavigateResponse>> AsyncNavigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::NavigateResponse>>(AsyncNavigateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::NavigateResponse>> PrepareAsyncNavigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::NavigateResponse>>(PrepareAsyncNavigateRaw(context, request, cq));
    }
    virtual ::grpc::Status GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::vaelix::control::GetTabInfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetTabInfoResponse>> AsyncGetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetTabInfoResponse>>(AsyncGetTabInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetTabInfoResponse>> PrepareAsyncGetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetTabInfoResponse>>(PrepareAsyncGetTabInfoRaw(context, request, cq));
    }
    // Browser control
    virtual ::grpc::Status Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::vaelix::control::BrowserShutdownResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::BrowserShutdownResponse>> AsyncShutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::BrowserShutdownResponse>>(AsyncShutdownRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::BrowserShutdownResponse>> PrepareAsyncShutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::BrowserShutdownResponse>>(PrepareAsyncShutdownRaw(context, request, cq));
    }
    virtual ::grpc::Status GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::vaelix::control::GetBrowserMetricsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetBrowserMetricsResponse>> AsyncGetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetBrowserMetricsResponse>>(AsyncGetMetricsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetBrowserMetricsResponse>> PrepareAsyncGetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetBrowserMetricsResponse>>(PrepareAsyncGetMetricsRaw(context, request, cq));
    }
    // Event streams (bidirectional for real-time updates)
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>> TabEvents(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>>(TabEventsRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>> AsyncTabEvents(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>>(AsyncTabEventsRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>> PrepareAsyncTabEvents(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>>(PrepareAsyncTabEventsRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Tab lifecycle management
      virtual void StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Browser control
      virtual void Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Event streams (bidirectional for real-time updates)
      virtual void TabEvents(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vaelix::control::TabEvent,::vaelix::control::TabEvent>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StartTabResponse>* AsyncStartTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StartTabResponse>* PrepareAsyncStartTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StopTabResponse>* AsyncStopTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::StopTabResponse>* PrepareAsyncStopTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::NavigateResponse>* AsyncNavigateRaw(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::NavigateResponse>* PrepareAsyncNavigateRaw(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetTabInfoResponse>* AsyncGetTabInfoRaw(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetTabInfoResponse>* PrepareAsyncGetTabInfoRaw(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::BrowserShutdownResponse>* AsyncShutdownRaw(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::BrowserShutdownResponse>* PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetBrowserMetricsResponse>* AsyncGetMetricsRaw(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vaelix::control::GetBrowserMetricsResponse>* PrepareAsyncGetMetricsRaw(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* TabEventsRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* AsyncTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* PrepareAsyncTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::vaelix::control::StartTabResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>> AsyncStartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>>(AsyncStartTabRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>> PrepareAsyncStartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>>(PrepareAsyncStartTabRaw(context, request, cq));
    }
    ::grpc::Status StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::vaelix::control::StopTabResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>> AsyncStopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>>(AsyncStopTabRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>> PrepareAsyncStopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>>(PrepareAsyncStopTabRaw(context, request, cq));
    }
    ::grpc::Status Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::vaelix::control::NavigateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>> AsyncNavigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>>(AsyncNavigateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>> PrepareAsyncNavigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>>(PrepareAsyncNavigateRaw(context, request, cq));
    }
    ::grpc::Status GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::vaelix::control::GetTabInfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>> AsyncGetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>>(AsyncGetTabInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>> PrepareAsyncGetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>>(PrepareAsyncGetTabInfoRaw(context, request, cq));
    }
    ::grpc::Status Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::vaelix::control::BrowserShutdownResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>> AsyncShutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>>(AsyncShutdownRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>> PrepareAsyncShutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>>(PrepareAsyncShutdownRaw(context, request, cq));
    }
    ::grpc::Status GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::vaelix::control::GetBrowserMetricsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>> AsyncGetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>>(AsyncGetMetricsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>> PrepareAsyncGetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>>(PrepareAsyncGetMetricsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>> TabEvents(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>>(TabEventsRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>> AsyncTabEvents(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>>(AsyncTabEventsRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>> PrepareAsyncTabEvents(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>>(PrepareAsyncTabEventsRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response, std::function<void(::grpc::Status)>) override;
      void StartTab(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response, std::function<void(::grpc::Status)>) override;
      void StopTab(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response, std::function<void(::grpc::Status)>) override;
      void Navigate(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response, std::function<void(::grpc::Status)>) override;
      void GetTabInfo(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response, std::function<void(::grpc::Status)>) override;
      void Shutdown(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetMetrics(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void TabEvents(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::vaelix::control::TabEvent,::vaelix::control::TabEvent>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>* AsyncStartTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::StartTabResponse>* PrepareAsyncStartTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StartTabRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>* AsyncStopTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::StopTabResponse>* PrepareAsyncStopTabRaw(::grpc::ClientContext* context, const ::vaelix::control::StopTabRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>* AsyncNavigateRaw(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::NavigateResponse>* PrepareAsyncNavigateRaw(::grpc::ClientContext* context, const ::vaelix::control::NavigateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>* AsyncGetTabInfoRaw(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetTabInfoResponse>* PrepareAsyncGetTabInfoRaw(::grpc::ClientContext* context, const ::vaelix::control::GetTabInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>* AsyncShutdownRaw(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::BrowserShutdownResponse>* PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::vaelix::control::BrowserShutdownRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>* AsyncGetMetricsRaw(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vaelix::control::GetBrowserMetricsResponse>* PrepareAsyncGetMetricsRaw(::grpc::ClientContext* context, const ::vaelix::control::GetBrowserMetricsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* TabEventsRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* AsyncTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* PrepareAsyncTabEventsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartTab_;
    const ::grpc::internal::RpcMethod rpcmethod_StopTab_;
    const ::grpc::internal::RpcMethod rpcmethod_Navigate_;
    const ::grpc::internal::RpcMethod rpcmethod_GetTabInfo_;
    const ::grpc::internal::RpcMethod rpcmethod_Shutdown_;
    const ::grpc::internal::RpcMethod rpcmethod_GetMetrics_;
    const ::grpc::internal::RpcMethod rpcmethod_TabEvents_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Tab lifecycle management
    virtual ::grpc::Status StartTab(::grpc::ServerContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response);
    virtual ::grpc::Status StopTab(::grpc::ServerContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response);
    virtual ::grpc::Status Navigate(::grpc::ServerContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response);
    virtual ::grpc::Status GetTabInfo(::grpc::ServerContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response);
    // Browser control
    virtual ::grpc::Status Shutdown(::grpc::ServerContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response);
    virtual ::grpc::Status GetMetrics(::grpc::ServerContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response);
    // Event streams (bidirectional for real-time updates)
    virtual ::grpc::Status TabEvents(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartTab() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StartTabRequest* /*request*/, ::vaelix::control::StartTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartTab(::grpc::ServerContext* context, ::vaelix::control::StartTabRequest* request, ::grpc::ServerAsyncResponseWriter< ::vaelix::control::StartTabResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StopTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StopTab() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StopTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StopTabRequest* /*request*/, ::vaelix::control::StopTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopTab(::grpc::ServerContext* context, ::vaelix::control::StopTabRequest* request, ::grpc::ServerAsyncResponseWriter< ::vaelix::control::StopTabResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Navigate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Navigate() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Navigate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Navigate(::grpc::ServerContext* /*context*/, const ::vaelix::control::NavigateRequest* /*request*/, ::vaelix::control::NavigateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNavigate(::grpc::ServerContext* context, ::vaelix::control::NavigateRequest* request, ::grpc::ServerAsyncResponseWriter< ::vaelix::control::NavigateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTabInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetTabInfo() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetTabInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTabInfo(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetTabInfoRequest* /*request*/, ::vaelix::control::GetTabInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTabInfo(::grpc::ServerContext* context, ::vaelix::control::GetTabInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::vaelix::control::GetTabInfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Shutdown() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::vaelix::control::BrowserShutdownRequest* /*request*/, ::vaelix::control::BrowserShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShutdown(::grpc::ServerContext* context, ::vaelix::control::BrowserShutdownRequest* request, ::grpc::ServerAsyncResponseWriter< ::vaelix::control::BrowserShutdownResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMetrics() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetBrowserMetricsRequest* /*request*/, ::vaelix::control::GetBrowserMetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetrics(::grpc::ServerContext* context, ::vaelix::control::GetBrowserMetricsRequest* request, ::grpc::ServerAsyncResponseWriter< ::vaelix::control::GetBrowserMetricsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TabEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TabEvents() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_TabEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TabEvents(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTabEvents(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(6, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartTab<WithAsyncMethod_StopTab<WithAsyncMethod_Navigate<WithAsyncMethod_GetTabInfo<WithAsyncMethod_Shutdown<WithAsyncMethod_GetMetrics<WithAsyncMethod_TabEvents<Service > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StartTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StartTab() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vaelix::control::StartTabRequest* request, ::vaelix::control::StartTabResponse* response) { return this->StartTab(context, request, response); }));}
    void SetMessageAllocatorFor_StartTab(
        ::grpc::MessageAllocator< ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StartTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StartTabRequest* /*request*/, ::vaelix::control::StartTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartTab(
      ::grpc::CallbackServerContext* /*context*/, const ::vaelix::control::StartTabRequest* /*request*/, ::vaelix::control::StartTabResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StopTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StopTab() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vaelix::control::StopTabRequest* request, ::vaelix::control::StopTabResponse* response) { return this->StopTab(context, request, response); }));}
    void SetMessageAllocatorFor_StopTab(
        ::grpc::MessageAllocator< ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StopTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StopTabRequest* /*request*/, ::vaelix::control::StopTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopTab(
      ::grpc::CallbackServerContext* /*context*/, const ::vaelix::control::StopTabRequest* /*request*/, ::vaelix::control::StopTabResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Navigate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Navigate() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vaelix::control::NavigateRequest* request, ::vaelix::control::NavigateResponse* response) { return this->Navigate(context, request, response); }));}
    void SetMessageAllocatorFor_Navigate(
        ::grpc::MessageAllocator< ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Navigate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Navigate(::grpc::ServerContext* /*context*/, const ::vaelix::control::NavigateRequest* /*request*/, ::vaelix::control::NavigateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Navigate(
      ::grpc::CallbackServerContext* /*context*/, const ::vaelix::control::NavigateRequest* /*request*/, ::vaelix::control::NavigateResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetTabInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetTabInfo() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vaelix::control::GetTabInfoRequest* request, ::vaelix::control::GetTabInfoResponse* response) { return this->GetTabInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetTabInfo(
        ::grpc::MessageAllocator< ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetTabInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTabInfo(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetTabInfoRequest* /*request*/, ::vaelix::control::GetTabInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTabInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::vaelix::control::GetTabInfoRequest* /*request*/, ::vaelix::control::GetTabInfoResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Shutdown() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vaelix::control::BrowserShutdownRequest* request, ::vaelix::control::BrowserShutdownResponse* response) { return this->Shutdown(context, request, response); }));}
    void SetMessageAllocatorFor_Shutdown(
        ::grpc::MessageAllocator< ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::vaelix::control::BrowserShutdownRequest* /*request*/, ::vaelix::control::BrowserShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Shutdown(
      ::grpc::CallbackServerContext* /*context*/, const ::vaelix::control::BrowserShutdownRequest* /*request*/, ::vaelix::control::BrowserShutdownResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMetrics() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vaelix::control::GetBrowserMetricsRequest* request, ::vaelix::control::GetBrowserMetricsResponse* response) { return this->GetMetrics(context, request, response); }));}
    void SetMessageAllocatorFor_GetMetrics(
        ::grpc::MessageAllocator< ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetBrowserMetricsRequest* /*request*/, ::vaelix::control::GetBrowserMetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::vaelix::control::GetBrowserMetricsRequest* /*request*/, ::vaelix::control::GetBrowserMetricsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_TabEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TabEvents() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackBidiHandler< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->TabEvents(context); }));
    }
    ~WithCallbackMethod_TabEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TabEvents(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* TabEvents(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StartTab<WithCallbackMethod_StopTab<WithCallbackMethod_Navigate<WithCallbackMethod_GetTabInfo<WithCallbackMethod_Shutdown<WithCallbackMethod_GetMetrics<WithCallbackMethod_TabEvents<Service > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartTab() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StartTabRequest* /*request*/, ::vaelix::control::StartTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StopTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StopTab() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StopTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StopTabRequest* /*request*/, ::vaelix::control::StopTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Navigate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Navigate() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Navigate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Navigate(::grpc::ServerContext* /*context*/, const ::vaelix::control::NavigateRequest* /*request*/, ::vaelix::control::NavigateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetTabInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetTabInfo() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetTabInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTabInfo(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetTabInfoRequest* /*request*/, ::vaelix::control::GetTabInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Shutdown() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::vaelix::control::BrowserShutdownRequest* /*request*/, ::vaelix::control::BrowserShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMetrics() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetBrowserMetricsRequest* /*request*/, ::vaelix::control::GetBrowserMetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TabEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TabEvents() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_TabEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TabEvents(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartTab() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StartTabRequest* /*request*/, ::vaelix::control::StartTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartTab(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StopTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StopTab() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StopTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StopTabRequest* /*request*/, ::vaelix::control::StopTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopTab(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Navigate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Navigate() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Navigate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Navigate(::grpc::ServerContext* /*context*/, const ::vaelix::control::NavigateRequest* /*request*/, ::vaelix::control::NavigateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNavigate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetTabInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetTabInfo() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetTabInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTabInfo(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetTabInfoRequest* /*request*/, ::vaelix::control::GetTabInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTabInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Shutdown() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::vaelix::control::BrowserShutdownRequest* /*request*/, ::vaelix::control::BrowserShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShutdown(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMetrics() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetBrowserMetricsRequest* /*request*/, ::vaelix::control::GetBrowserMetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetrics(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TabEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TabEvents() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_TabEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TabEvents(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTabEvents(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(6, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StartTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StartTab() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartTab(context, request, response); }));
    }
    ~WithRawCallbackMethod_StartTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StartTabRequest* /*request*/, ::vaelix::control::StartTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartTab(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StopTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StopTab() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StopTab(context, request, response); }));
    }
    ~WithRawCallbackMethod_StopTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StopTabRequest* /*request*/, ::vaelix::control::StopTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopTab(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Navigate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Navigate() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Navigate(context, request, response); }));
    }
    ~WithRawCallbackMethod_Navigate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Navigate(::grpc::ServerContext* /*context*/, const ::vaelix::control::NavigateRequest* /*request*/, ::vaelix::control::NavigateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Navigate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetTabInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetTabInfo() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetTabInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetTabInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTabInfo(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetTabInfoRequest* /*request*/, ::vaelix::control::GetTabInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTabInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Shutdown() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Shutdown(context, request, response); }));
    }
    ~WithRawCallbackMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::vaelix::control::BrowserShutdownRequest* /*request*/, ::vaelix::control::BrowserShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Shutdown(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMetrics() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMetrics(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetBrowserMetricsRequest* /*request*/, ::vaelix::control::GetBrowserMetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TabEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TabEvents() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->TabEvents(context); }));
    }
    ~WithRawCallbackMethod_TabEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TabEvents(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::vaelix::control::TabEvent, ::vaelix::control::TabEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* TabEvents(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartTab() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vaelix::control::StartTabRequest, ::vaelix::control::StartTabResponse>* streamer) {
                       return this->StreamedStartTab(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StartTabRequest* /*request*/, ::vaelix::control::StartTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartTab(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vaelix::control::StartTabRequest,::vaelix::control::StartTabResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StopTab : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StopTab() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vaelix::control::StopTabRequest, ::vaelix::control::StopTabResponse>* streamer) {
                       return this->StreamedStopTab(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StopTab() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StopTab(::grpc::ServerContext* /*context*/, const ::vaelix::control::StopTabRequest* /*request*/, ::vaelix::control::StopTabResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStopTab(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vaelix::control::StopTabRequest,::vaelix::control::StopTabResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Navigate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Navigate() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vaelix::control::NavigateRequest, ::vaelix::control::NavigateResponse>* streamer) {
                       return this->StreamedNavigate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Navigate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Navigate(::grpc::ServerContext* /*context*/, const ::vaelix::control::NavigateRequest* /*request*/, ::vaelix::control::NavigateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNavigate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vaelix::control::NavigateRequest,::vaelix::control::NavigateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetTabInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetTabInfo() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vaelix::control::GetTabInfoRequest, ::vaelix::control::GetTabInfoResponse>* streamer) {
                       return this->StreamedGetTabInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetTabInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTabInfo(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetTabInfoRequest* /*request*/, ::vaelix::control::GetTabInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetTabInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vaelix::control::GetTabInfoRequest,::vaelix::control::GetTabInfoResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Shutdown : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Shutdown() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vaelix::control::BrowserShutdownRequest, ::vaelix::control::BrowserShutdownResponse>* streamer) {
                       return this->StreamedShutdown(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Shutdown() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Shutdown(::grpc::ServerContext* /*context*/, const ::vaelix::control::BrowserShutdownRequest* /*request*/, ::vaelix::control::BrowserShutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedShutdown(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vaelix::control::BrowserShutdownRequest,::vaelix::control::BrowserShutdownResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMetrics() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vaelix::control::GetBrowserMetricsRequest, ::vaelix::control::GetBrowserMetricsResponse>* streamer) {
                       return this->StreamedGetMetrics(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::vaelix::control::GetBrowserMetricsRequest* /*request*/, ::vaelix::control::GetBrowserMetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMetrics(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vaelix::control::GetBrowserMetricsRequest,::vaelix::control::GetBrowserMetricsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartTab<WithStreamedUnaryMethod_StopTab<WithStreamedUnaryMethod_Navigate<WithStreamedUnaryMethod_GetTabInfo<WithStreamedUnaryMethod_Shutdown<WithStreamedUnaryMethod_GetMetrics<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartTab<WithStreamedUnaryMethod_StopTab<WithStreamedUnaryMethod_Navigate<WithStreamedUnaryMethod_GetTabInfo<WithStreamedUnaryMethod_Shutdown<WithStreamedUnaryMethod_GetMetrics<Service > > > > > > StreamedService;
};

}  // namespace control
}  // namespace vaelix


#endif  // GRPC_control_2eproto__INCLUDED
